=== UniTime/unitime/JavaSource/menu.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 
<!ELEMENT unitime-menu (menu|item|separator|remove)* >
 
<!ELEMENT menu ((parameter)*, (condition|new-condition)?,  (menu|item|separator|remove)*) >
<!ATTLIST menu name CDATA #REQUIRED >
<!ATTLIST menu title CDATA #IMPLIED >
<!ATTLIST menu page CDATA #IMPLIED >
<!ATTLIST menu type (gwt|property) #IMPLIED >
<!ATTLIST menu target (download|dialog|eval|tab) #IMPLIED >
<!ATTLIST menu hash CDATA #IMPLIED >
 
<!ELEMENT separator ((condition|new-condition)?) >

<!ELEMENT item ((parameter)*, (condition|new-condition)?) > 
<!ATTLIST item name CDATA #REQUIRED >
<!ATTLIST item page CDATA #REQUIRED >
<!ATTLIST item type (gwt|property|page) #IMPLIED >
<!ATTLIST item target (download|dialog|eval|tab) #IMPLIED >
<!ATTLIST item hash CDATA #IMPLIED >

<!ELEMENT condition (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight|hasPermission)* >

<!ELEMENT and (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight|hasPermission)* >
<!ELEMENT or (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight|hasPermission)* >
<!ELEMENT not (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight|hasPermission)* >
 
 <!ELEMENT isAuthenticated EMPTY >
 
<!ELEMENT hasRole EMPTY >
<!ATTLIST hasRole name CDATA #IMPLIED >

<!ELEMENT hasProperty EMPTY >
<!ATTLIST hasProperty name CDATA #REQUIRED >

<!ELEMENT propertyEquals EMPTY >
<!ATTLIST propertyEquals name CDATA #REQUIRED >
<!ATTLIST propertyEquals value CDATA #REQUIRED >
<!ATTLIST propertyEquals defaultValue CDATA #IMPLIED >

<!ELEMENT hasRight EMPTY >
<!ATTLIST hasRight name (canSeeCourses|canSeeTimetable|hasASolverGroup|canDoTimetable|canAudit|canSectionStudents|isSectioningEnabled|isRegistrationEnabled|canSeeEvents|isChameleon|hasPersonalReport|isStudent|hasRoomAvailability|canSeeExams|canTimetableExams|hasCourseReports|hasExamReports|hasStudentReports|hasEventReports|isInstructor|hasPointInTimeDataReports) #REQUIRED >

<!ELEMENT parameter (#PCDATA) >
<!ATTLIST parameter name CDATA #REQUIRED >
<!ATTLIST parameter value CDATA #IMPLIED >

<!ELEMENT hasPermission EMPTY >
<!ATTLIST hasPermission name CDATA #REQUIRED >
<!ATTLIST hasPermission authority (current|session|role|any) #IMPLIED >
<!ATTLIST hasPermission check (true|false) #IMPLIED >

<!-- custom menu -->
<!ATTLIST item position CDATA #IMPLIED >

<!ELEMENT remove EMPTY > 
<!ATTLIST remove name CDATA #REQUIRED >

<!ELEMENT new-condition (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight|hasPermission)* >

=== UniTime/unitime/JavaSource/menu.xml
<!DOCTYPE unitime-menu PUBLIC "-//UniTime//UniTime Menu DTD/EN" "http://www.unitime.org/interface/menu.dtd">

<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
<unitime-menu>
	<menu name="Courses" title="Course Timetabling">
		<condition>
			<or>
				<hasPermission name="InstructionalOfferings"/>
				<hasPermission name="Classes"/>
				<hasPermission name="HQLReportsCourses"/>
				<hasPermission name="ClassAssignments"/>
				<hasPermission name="InstructorDetail"/>
				<hasPermission name="InstructorSurvey" authority="session"/>
			</or>
		</condition>
		<menu name="Input Data" title="Course Timetabling Input Data">
			<item name="Instructional Offerings" page="instructionalOfferingSearch.action">
				<condition>
					<hasPermission name="InstructionalOfferings"/>
					<propertyEquals name="unitime.legacy.course.offerings" value="true" defaultValue="false"/>
				</condition>
			</item>
			<item name="Instructional Offerings" page="offerings" type="gwt">
				<condition>
					<hasPermission name="InstructionalOfferings"/>
					<propertyEquals name="unitime.legacy.course.offerings" value="false" defaultValue="false"/>
				</condition>
			</item>
			<item name="Classes" page="classSearch.action">
				<condition>
					<hasPermission name="Classes"/>
					<propertyEquals name="unitime.legacy.course.classes" value="true" defaultValue="false"/>
				</condition>
			</item>
			<item name="Classes" page="classSearch" type="gwt">
				<condition>
					<hasPermission name="Classes"/>
					<propertyEquals name="unitime.legacy.course.classes" value="false" defaultValue="false"/>
				</condition>
			</item>
			<separator/>
			<menu name="Curricula" page="curricula" type="gwt">
				<condition>
					<hasPermission name="CurriculumView"/>
				</condition>
				<item name="Projection Rules" page="curprojrules" type="gwt">
					<condition>
						<hasPermission name="CurriculumProjectionRulesDetail"/>
					</condition>
				</item>
			</menu>
			<separator/>
			<item name="Instructors" page="instructorSearch.action">
				<condition>
					<hasPermission name="Instructors"/>
					<propertyEquals name="unitime.legacy.instructors" value="true" defaultValue="false"/>
				</condition>
			</item>
			<item name="Instructors" page="instructors" type="gwt">
				<condition>
					<hasPermission name="Instructors"/>
					<propertyEquals name="unitime.legacy.instructors" value="false" defaultValue="false"/>
				</condition>
			</item>
			<item name="Instructor Attributes" page="instructorattributes" type="gwt">
				<condition>
					<hasPermission name="InstructorAttributes"/>
				</condition>
			</item>
			<item name="Instructor Detail" page="instructorDetail.action">
				<condition>
					<hasPermission name="InstructorDetail"/>
					<not>
						<hasPermission name="Instructors"/>
					</not>
				</condition>
			</item>
			<item name="Instructor Survey" page="instructorSurvey" type="gwt">
				<condition>
					<hasPermission name="InstructorSurvey" authority="session"/>
					<not>
						<hasPermission name="Instructors"/>
					</not>
				</condition>
			</item>
			<separator/>
			<menu name="Rooms" page="rooms" type="gwt">
				<parameter name="mode">courses</parameter>
				<condition>
					<hasPermission name="Rooms"/>
				</condition>
				<item name="Room Features" page="roomfeatures" type="gwt">
					<parameter name="mode">courses</parameter>
					<condition>
						<hasPermission name="RoomFeatures"/>
					</condition>
				</item>
				<item name="Room Groups" page="roomgroups" type="gwt">
					<parameter name="mode">courses</parameter>
					<condition>
						<hasPermission name="RoomGroups"/>
					</condition>
				</item>
				<item name="Travel Times" page="traveltimes" type="gwt">
					<condition>
						<hasPermission name="TravelTimesLoad"/>
					</condition>
				</item>
			</menu>
			<separator/>
			<item name="Distribution Preferences" page="distributionPrefs.action">
				<condition>
					<hasPermission name="DistributionPreferences"/>
					<propertyEquals name="unitime.legacy.distributions" value="true"/>
				</condition>
			</item>
			<item name="Distribution Preferences" page="distributions" type="gwt">
				<condition>
					<hasPermission name="DistributionPreferences"/>
					<propertyEquals name="unitime.legacy.distributions" value="false"/>
				</condition>
			</item>
			<item name="Reservations" page="reservations" type="gwt">
				<condition>
					<hasPermission name="Reservations"/>
				</condition>
			</item>
			<item name="Class Assignments" page="classAssignmentsReportSearch.action">
				<condition>
					<hasPermission name="ClassAssignments"/>
					<propertyEquals name="unitime.legacy.course.assignments" value="true" defaultValue="false"/>
				</condition>
			</item>
			<item name="Class Assignments" page="classAssignments" type="gwt">
				<condition>
					<hasPermission name="ClassAssignments"/>
					<propertyEquals name="unitime.legacy.course.assignments" value="false" defaultValue="false"/>
				</condition>
			</item>
		</menu>
		<menu name="Course Timetabling" title="Course Timetabling Solver">
			<condition>
				<or>
					<hasPermission name="CourseTimetabling"/>
					<hasPermission name="Timetables"/>
				</or>
			</condition>
			<item name="Saved Timetables" page="listSolutions" type="gwt">
				<condition>
					<hasPermission name="Timetables"/>
				</condition>
			</item>
			<item name="Solver" page="solver" type="gwt">
				<parameter name="type">course</parameter>
				<condition>
					<hasPermission name="Solver"/>
				</condition>
			</item>
			<item name="Timetable Grid" page="timetableGrid" type="gwt">
				<condition>
					<hasPermission name="TimetableGrid"/>
				</condition>
			</item>
			<separator/>
			<item name="Assigned Classes" page="assignedClasses" type="gwt">
				<condition>
					<hasPermission name="AssignedClasses"/>
				</condition>
			</item>
			<item name="Not-assigned Classes" page="notAssignedClasses" type="gwt">
				<condition>
					<hasPermission name="NotAssignedClasses"/>
				</condition>
			</item>
			<item name="Changes" page="solutionChanges" type="gwt">
				<condition>
					<hasPermission name="SolutionChanges"/>
				</condition>
			</item>
			<item name="History" page="assignmentHistory" type="gwt">
				<condition>
					<hasPermission name="AssignmentHistory"/>
				</condition>
			</item>
			<item name="Conflict Statistics" page="cbs" type="gwt">
				<condition>
					<hasPermission name="ConflictStatistics"/>
				</condition>
			</item>
			<item name="Solver Log" page="solverlog" type="gwt">
				<parameter name="type">course</parameter>
				<condition>
					<hasPermission name="SolverLog"/>
				</condition>
			</item>
			<item name="Reports" page="solutionReports" type="gwt">
				<condition>
					<hasPermission name="SolutionReports"/>
				</condition>
			</item>
		</menu>
		<menu name="Course Audit" title="Course Timetabling Audit">
			<condition>
				<hasPermission name="CourseTimetablingAudit"/>
			</condition>
			<item name="Solver" page="solver" type="gwt">
				<parameter name="type">course</parameter>
				<condition>
					<hasPermission name="Solver"/>
				</condition>
			</item>
			<item name="Conflict Statistics" page="cbs" type="gwt">
				<condition>
					<hasPermission name="ConflictStatistics"/>
				</condition>
			</item>
			<item name="Solver Log" page="solverlog" type="gwt">
				<parameter name="type">course</parameter>
				<condition>
					<hasPermission name="SolverLog"/>
				</condition>
			</item>
			<item name="Reports" page="solutionReports" type="gwt">
				<condition>
					<hasPermission name="SolutionReports"/>
				</condition>
			</item>
		</menu>
		<menu name="Instructor Scheduling">
			<condition>
				<hasPermission name="InstructorSchedulingSolver"/>
			</condition>
			<item name="Instructor Scheduling Solver" page="solver" type="gwt">
				<parameter name="type">instructor</parameter>
			</item>
			<item name="Solver Log" page="solverlog" type="gwt">
				<parameter name="type">instructor</parameter>
				<condition>
					<hasPermission name="InstructorSchedulingSolverLog"/>
				</condition>
			</item>
			<separator/>
			<item name="Assigned Teaching Requests" page="teachingRequests" type="gwt">
				<parameter name="assigned">true</parameter>
			</item>
			<item name="Not-Assigned Teaching Requests" page="teachingRequests" type="gwt">
				<parameter name="assigned">false</parameter>
			</item>
			<item name="Teaching Assignments" page="teachingAssignments" type="gwt"/>
			<item name="Assignment Changes" page="teachingAssignmentChanges" type="gwt"/>
		</menu>
		<item name="Reports" page="hql" type="gwt">
			<parameter name="appearance">courses</parameter>
			<condition>
				<hasPermission name="HQLReportsCourses"/>
			</condition>
		</item>
		<item name="Point In Time Data Reports" page="pointInTimeDataReports" type="gwt">
			<condition>
				<hasPermission name="PointInTimeDataReports"/>
			</condition>
		</item>
	</menu>
	<menu name="Curricula" title="Curriculum Timetabling">
		<condition>
			<hasPermission name="CurriculumView"/>
			<not>
				<hasPermission name="Classes"/>
				<hasPermission name="InstructionalOfferings"/>
			</not>
		</condition>
		<item name="Curricula" page="curricula" type="gwt">
			<condition>
