=== UniTime/unitime/Documentation/Interfaces/CourseOfferingExport.dtd
<!-- 
 * UniTime 3.2 (University Timetabling Application)
 * Copyright (C) 2008 - 2010, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->

<!ELEMENT class ( class*, date*, time?, (room|location|instructor|meeting|meetsWith)* ) >
<!-- displayInScheduleBook has been deprecated in UniTime 3.4, use studentScheduling instead -->
<!ATTLIST class displayInScheduleBook ( false | true ) #IMPLIED >
<!-- studentScheduling was introduced in UniTime 3.4, if false class appears like it has zero limit in (both batch and online) student scheduling -->
<!ATTLIST class studentScheduling ( false | true ) #IMPLIED >
<!ATTLIST class id CDATA #IMPLIED >
<!ATTLIST class limit NMTOKEN #REQUIRED >
<!ATTLIST class scheduleNote CDATA #IMPLIED >
<!ATTLIST class suffix CDATA #REQUIRED >
<!ATTLIST class type CDATA #REQUIRED >

<!ELEMENT config ( (subpart|class)* ) >
<!ATTLIST config limit NMTOKEN #REQUIRED >
<!ATTLIST config name CDATA #REQUIRED >

<!ELEMENT consent EMPTY >
<!ATTLIST consent type CDATA #REQUIRED >

<!ELEMENT course ( consent?, courseCredit? ) >
<!ATTLIST course id CDATA #IMPLIED >
<!ATTLIST course controlling ( false | true ) #IMPLIED >
<!ATTLIST course courseNbr NMTOKEN #REQUIRED >
<!ATTLIST course scheduleBookNote CDATA #IMPLIED >
<!ATTLIST course subject CDATA #REQUIRED >
<!ATTLIST course title CDATA #IMPLIED >

<!ELEMENT courseCredit EMPTY >
<!ATTLIST courseCredit creditFormat ( arrangeHours | fixedUnit | variableMinMax | variableRange ) #REQUIRED >
<!ATTLIST courseCredit creditType ( collegiate | equivalent | mastersCredit | phdThesisCredit | continuingEdUnits ) #REQUIRED >
<!ATTLIST courseCredit creditUnitType CDATA #REQUIRED >
<!ATTLIST courseCredit fixedCredit CDATA #IMPLIED >
<!ATTLIST courseCredit fractionalCreditAllowed ( false | true ) #IMPLIED >
<!ATTLIST courseCredit maximumCredit CDATA #IMPLIED >
<!ATTLIST courseCredit minimumCredit CDATA #IMPLIED >

<!-- designatorRequired toggle is deprecated since UniTime 3.4 -->
<!ELEMENT designatorRequired EMPTY >

<!ELEMENT instructor EMPTY >
<!ATTLIST instructor fname CDATA #IMPLIED >
<!ATTLIST instructor id NMTOKEN #REQUIRED >
<!ATTLIST instructor lead ( false | true ) #IMPLIED >
<!ATTLIST instructor lname CDATA #IMPLIED >
<!ATTLIST instructor mname CDATA #IMPLIED >
<!ATTLIST instructor title CDATA #IMPLIED >
<!ATTLIST instructor share NMTOKEN #IMPLIED >

<!ELEMENT offering ( designatorRequired?, courseCredit?, course+, config*, exam* ) >
<!ATTLIST offering action CDATA #IMPLIED >
<!ATTLIST offering id NMTOKEN #REQUIRED >
<!ATTLIST offering offered  ( false | true ) #REQUIRED >

<!ELEMENT offerings ( offering* ) >
<!ATTLIST offerings campus NMTOKEN #REQUIRED >
<!ATTLIST offerings term NMTOKEN #REQUIRED >
<!ATTLIST offerings year NMTOKEN #REQUIRED >
<!ATTLIST offerings dateFormat CDATA #IMPLIED >
<!ATTLIST offerings timeFormat CDATA #IMPLIED >
<!ATTLIST offerings useMeetsWith ( false | true ) #IMPLIED >
<!ATTLIST offerings created CDATA #IMPLIED >
<!ATTLIST offerings incremental ( false | true ) "false" > 

<!ELEMENT room EMPTY >
<!ATTLIST room building CDATA #REQUIRED >
<!ATTLIST room id CDATA #IMPLIED >
<!ATTLIST room roomNbr CDATA #REQUIRED >

<!ELEMENT location EMPTY >
<!ATTLIST location name CDATA #REQUIRED >

<!ELEMENT subpart ( subpartCredit*, subpart* ) >
<!ATTLIST subpart minPerWeek NMTOKEN #REQUIRED >
<!ATTLIST subpart suffix CDATA #IMPLIED >
<!ATTLIST subpart type CDATA #REQUIRED >

<!ELEMENT subpartCredit EMPTY >
<!ATTLIST subpartCredit creditFormat ( arrangeHours | fixedUnit | variableMinMax | variableRange ) #REQUIRED >
<!ATTLIST subpartCredit creditType ( collegiate | equivalent | mastersCredit | phdThesisCredit ) #REQUIRED >
<!ATTLIST subpartCredit creditUnitType CDATA #REQUIRED >
<!ATTLIST subpartCredit fixedCredit CDATA #IMPLIED >
<!ATTLIST subpartCredit fractionalCreditAllowed ( false | true ) #IMPLIED >
<!ATTLIST subpartCredit maximumCredit CDATA #IMPLIED >
<!ATTLIST subpartCredit minimumCredit CDATA #IMPLIED >

<!ELEMENT time EMPTY >
<!ATTLIST time days NMTOKEN #REQUIRED >
<!ATTLIST time endTime NMTOKEN #REQUIRED >
<!ATTLIST time startTime NMTOKEN #REQUIRED >
<!ATTLIST time timePattern CDATA #IMPLIED >

<!ELEMENT date EMPTY >
<!ATTLIST date endDate CDATA #REQUIRED >
<!ATTLIST date startDate CDATA #REQUIRED >

<!ELEMENT exam ( (class|course)*, instructor*, (period, (room|location)*)?) >
<!ATTLIST exam id CDATA #REQUIRED >
<!ATTLIST exam name CDATA #REQUIRED >
<!ATTLIST exam size NMTOKEN #REQUIRED >
<!ATTLIST exam note CDATA #IMPLIED >
<!ATTLIST exam length NMTOKEN #IMPLIED >
<!ATTLIST exam seatingType ( normal | exam) #IMPLIED >
<!ATTLIST exam type ( final | midterm) #REQUIRED >

<!ELEMENT period EMPTY >
<!ATTLIST period date CDATA #REQUIRED >
<!ATTLIST period startTime NMTOKEN #REQUIRED >
<!ATTLIST period endTime NMTOKEN #REQUIRED >

<!ELEMENT meeting EMPTY >
<!ATTLIST meeting endDate CDATA #IMPLIED >
<!ATTLIST meeting startDate CDATA #IMPLIED >
<!ATTLIST meeting startTime NMTOKEN #REQUIRED >
<!ATTLIST meeting endTime NMTOKEN #REQUIRED >
<!ATTLIST meeting days CDATA #REQUIRED >
<!ATTLIST meeting building CDATA #IMPLIED >
<!ATTLIST meeting room CDATA #IMPLIED >
<!ATTLIST meeting location CDATA #IMPLIED >

<!ELEMENT meetsWith EMPTY >
<!ATTLIST meetsWith id CDATA #REQUIRED >

<!ELEMENT exams ( exam* ) >
<!ATTLIST exams campus NMTOKEN #REQUIRED >
<!ATTLIST exams term NMTOKEN #REQUIRED >
<!ATTLIST exams year NMTOKEN #REQUIRED >
<!ATTLIST exams dateFormat CDATA #IMPLIED >
<!ATTLIST exams timeFormat CDATA #IMPLIED >
<!ATTLIST exams created CDATA #IMPLIED >
<!ATTLIST exams type ( all | final | midterm) #REQUIRED >

=== UniTime/unitime/branches/dev_cluster/Documentation/Interfaces/Examples/courseOfferingExport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE offerings PUBLIC "-//UniTime//DTD University Course Timetabling/EN" "http://www.unitime.org/interface/CourseOfferingExport.dtd">

<!-- 
 * UniTime 3.2 (University Timetabling Application)
 * Copyright (C) 2008 - 2010, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->

<offerings campus="PuWL" year="2006" term="Fall">
	<offering id="10234" offered="true" action="update|delete|insert">
		<consent type="department|instructor"/>
		<courseCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="3"/>
		<course subject="A&amp;AE" courseNbr="101" controlling="true" title="" scheduleBookNote=""/>
		<course subject="A&amp;AE" courseNbr="101H" controlling="false" title="" scheduleBookNote=""/>
		<config name="1" limit="20">
			<subpart type="Lec" suffix="" minPerWeek="50">
			  		<subpartCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="1"/>
				<subpart type="Rec" suffix="" minPerWeek="100">
			  		<subpartCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="1"/>
					<subpart type="Rec" suffix="a" minPerWeek="50"/>
				</subpart>
				<subpart type="Lab" suffix="" minPerWeek="100">
 			  		<subpartCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="1"/>
				</subpart>
			</subpart>
			<subpart type="Lab" suffix="" minPerWeek="150"/>
			<class id="" type="Lec" suffix="1" limit="20" scheduleNote="" studentScheduling="true">
				<class id="" type="Rec" suffix="1" limit="10">
					<class id="" type="Rec" suffix="1a" limit="10"/>
				</class>
				<class id="" type="Rec" suffix="2" limit="10">
					<class id="" type="Rec" suffix="2a" limit="10"/>
				</class>
				<date startDate="08/20" endDate="09/22"/> <!-- non-default date pattern -->
				<time days="MWF" startTime="0730" endTime="0820"/>
				<room id="" building="REC" roomNbr="101"/>
				<room id="" building="REC" roomNbr="102"/>
				<instructor id="23344" lname="" mname="" fname="" share="80" lead="true"/> <!-- only instructors that are allowed to be printed are included -->
				<instructor id="23435" lname="" mname="" fname="" share="20"/>
			</class>
			<class id="" type="Lab" suffix="1" limit="15"/>
			<class id="" type="Lab" suffix="2" limit="5"/>
		</config>
		<config name="2" limit="inf">
			<subpart type="Lec" suffix="" minPerWeek="100">
			  		<subpartCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="1"/>
			</subpart>
			<class id="" type="Lec" suffix="2">
				<!-- arrange hours class: no time element-->
				<location name="PIZZA HUT"/> <!-- non-university location -->
			</class>
		</config>
	</offering>
</offerings>

=== UniTime/unitime/branches/dev_mobile/Documentation/Interfaces/Examples/courseOfferingWithExamsExport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE offerings PUBLIC "-//UniTime//DTD University Course Timetabling/EN" "http://www.unitime.org/interface/CourseOfferingExport.dtd">

<!-- 
 * UniTime 3.2 (University Timetabling Application)
 * Copyright (C) 2008 - 2010, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->

<offerings campus="PuWL" year="2006" term="Fall">
	<offering id="10234" offered="true" action="update|delete|insert">
		<courseCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="3"/>
		<course subject="A&amp;AE" courseNbr="101" controlling="true" title="" scheduleBookNote="">
			<!-- Since UniTime 3.4, consent is on courses not on offerings -->
			<!-- DP for department, IN for instructor -->
			<consent type="DP|IN"/>
		</course>
		<course subject="A&amp;AE" courseNbr="101H" controlling="false" title="" scheduleBookNote="">
			<!-- Since UniTime 3.5, course credit is on courses not on offerings -->
			<!-- It is still allowed to have course credit on the offering (it acts as a default for all the courses of the offering) -->
			<courseCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="2"/>
		</course>
		<config name="1" limit="20">
			<subpart type="Lec" suffix="" minPerWeek="100">
			  		<subpartCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="1"/>
				<subpart type="Rec" suffix="" minPerWeek="50">
			  		<subpartCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="1"/>
				</subpart>
				<subpart type="Lab" suffix="" minPerWeek="100">
 			  		<subpartCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="1"/>
					<subpart type="Lab" suffix="a" minPerWeek="50"/>
				</subpart>
			</subpart>
			<subpart type="Lab" suffix="" minPerWeek="150"/>
			<class id="1001" type="Lec" suffix="1" limit="20" scheduleNote="" studentScheduling="true">
				<class id="1002" type="Rec" suffix="1" limit="10">
					<class id="1003" type="Rec" suffix="1a" limit="10"/>
				</class>
				<class id="1004" type="Rec" suffix="2" limit="10">
					<class id="1005" type="Rec" suffix="2a" limit="10"/>
				</class>
				<date startDate="08/20" endDate="09/22"/> <!-- non-default date pattern -->
				<time days="MWF" startTime="0730" endTime="0820"/>
				<room id="" building="REC" roomNbr="101"/>
				<room id="" building="REC" roomNbr="102"/>
				<instructor id="23344" lname="" mname="" fname="" share="0.8" lead="true"/> <!-- only instructors that are allowed to be printed are included -->
				<instructor id="23435" lname="" mname="" fname="" share="0.2"/>
			</class>
			<class id="1006" type="Lab" suffix="1" limit="15"/>
			<class id="1007" type="Lab" suffix="2" limit="5"/>
		</config>
		<config name="2" limit="inf">
			<subpart type="Lec" suffix="" minPerWeek="100">
			  		<subpartCredit creditType="collegiate" creditUnitType="semesterHours" creditFormat="fixedUnit" fixedCredit="1"/>
			</subpart>
			<class id="1008" type="Lec" suffix="2">
				<!-- arrange hours class: no time element-->
				<location name="PIZZA HUT"/> <!-- non-university location -->
			</class>
		</config>
		<exam id="1223" name="A&amp;AE 101" size="30" seatingType="exam" length="120" type="final"> <!-- an exam for the whole offering -->
			<instructor id="23344" lname="Doe" mname="" fname="Joe"/>
			<period date="08/21" startTime="0800" endTime="1000"/>
			<room id="" building="REC" roomNbr="101"/>
			<room id="" building="REC" roomNbr="102"/>
		</exam>
		<exam id="1224" name="A&amp;AE 101 Lec 1,2" size="20" seatingType="exam" length="60" type="midterm"> <!-- an midterm exam for two sections -->
			<class id="1001" type="Lec" suffix="1"/>
			<class id="1008" type="Lec" suffix="2"/>
			<period date="07/20" startTime="1830" endTime="1930"/>
			<room id="" building="REC" roomNbr="101"/>
		</exam>
		<!-- multiple exams may be present -->
	</offering>
</offerings>

=== UniTime/unitime/branches/dev_cluster/Documentation/Interfaces/Examples/courseOfferingsWithMeetings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE offerings PUBLIC "-//UniTime//DTD University Course Timetabling/EN" "http://www.unitime.org/interface/CourseOfferingExport.dtd">

<offerings campus="woebegon" year="2010" term="Fal" dateFormat="yyyy/MM/dd" timeFormat="HHmm" incremental="true">
	<offering id="ALG201" offered="true">
		<course subject="ALG" courseNbr="201" controlling="true"/>
		<config name="1" limit="20">
			<subpart type="Lec" minPerWeek="150">
				<subpart type="Rec" minPerWeek="100"/>
			</subpart>
			<class type="Lec" suffix="1" limit="20">
				<class type="Rec" suffix="1" limit="10">
					<!-- every Thursday through the semester -->
					<meeting startTime="1530" endTime="1730" days="R" location="MALL"/>
				</class>
				<class type="Rec" suffix="2" limit="10">
					<!-- meet just once on the given date -->
					<meeting startDate="2010/10/12" endDate="2010/10/12" startTime="1330" endTime="1530" days="MTWRFSU" building="EDUC" room="107"/>
				</class>
				<!-- meet every Monday, Wednesday, and Friday between 9:30 am and 10:20 am during the given dates -->
				<meeting startDate="2010/08/23" endDate="2010/09/03" startTime="0930" endTime="1030" days="MWF" building="EDUC" room="103"/>
				<meeting startDate="2010/09/08" endDate="2010/10/08" startTime="0930" endTime="1030" days="MWF" building="EDUC" room="103"/>
				<meeting startDate="2010/10/13" endDate="2010/11/22" startTime="0930" endTime="1030" days="MWF" building="EDUC" room="103"/>
				<meeting startDate="2010/11/29" endDate="2010/12/10" startTime="0930" endTime="1030" days="MWF" building="EDUC" room="103"/>
			</class>
		</config>
	</offering>
</offerings>
