=== UniTime/unitime/Documentation/Interfaces/StudentSectioning.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->

<!ELEMENT acadArea ( major*, minor* ) >
<!ATTLIST acadArea abbv CDATA #REQUIRED >
<!ATTLIST acadArea classification CDATA #REQUIRED >

<!ELEMENT acknowledgement ( message* ) >
<!ATTLIST acknowledgement result ( ok | fail ) #REQUIRED >

<!ELEMENT alternative (preferences?) >
<!ATTLIST alternative courseNumber CDATA #REQUIRED >
<!ATTLIST alternative subjectArea CDATA #REQUIRED >
<!ATTLIST alternative title CDATA #IMPLIED >

<!ELEMENT cancelStudent EMPTY >
<!ATTLIST cancelStudent delete ( true | false ) "false" >

<!ELEMENT choice ( depends* ) >
<!ATTLIST choice available ( false | true ) #IMPLIED >
<!ATTLIST choice date CDATA #IMPLIED >
<!ATTLIST choice days CDATA #IMPLIED >
<!ATTLIST choice endTime CDATA #IMPLIED >
<!ATTLIST choice id CDATA #REQUIRED >
<!ATTLIST choice instructor CDATA #IMPLIED >
<!ATTLIST choice selection ( select | wait ) #IMPLIED >
<!ATTLIST choice startTime CDATA #IMPLIED >
<!ATTLIST choice time CDATA #IMPLIED >

<!ELEMENT class ( choice* ) >
<!ATTLIST class assignmentId CDATA #IMPLIED >
<!ATTLIST class date CDATA #IMPLIED >
<!ATTLIST class days CDATA #IMPLIED >
<!ATTLIST class endTime CDATA #IMPLIED >
<!ATTLIST class id CDATA #IMPLIED >
<!ATTLIST class instructor CDATA #IMPLIED >
<!ATTLIST class location CDATA #IMPLIED >
<!ATTLIST class name CDATA #IMPLIED >
<!ATTLIST class note CDATA #IMPLIED >
<!ATTLIST class parent CDATA #IMPLIED >
<!ATTLIST class startTime CDATA #IMPLIED >
<!ATTLIST class time CDATA #IMPLIED >
<!ATTLIST class externalId CDATA #IMPLIED >
<!ATTLIST class type CDATA #IMPLIED >
<!ATTLIST class suffix CDATA #IMPLIED >
<!ATTLIST class required ( false | true ) #IMPLIED >

<!ELEMENT courseOffering ( alternative | class | preferences)* >
<!ATTLIST courseOffering alternative ( false | true ) #IMPLIED >
<!ATTLIST courseOffering courseNumber CDATA #REQUIRED >
<!ATTLIST courseOffering credit CDATA #IMPLIED >
<!ATTLIST courseOffering subjectArea CDATA #REQUIRED >
<!ATTLIST courseOffering title CDATA #IMPLIED >
<!ATTLIST courseOffering waitlist ( false | true ) #IMPLIED >
<!ATTLIST courseOffering critical ( false | true ) #IMPLIED >

<!ELEMENT courseRequests ( courseOffering | freeTime )* >
<!ATTLIST courseRequests distribution ( dense | spread ) #IMPLIED >

<!ELEMENT depends ( depends* ) >
<!ATTLIST depends choice CDATA #REQUIRED >
<!ATTLIST depends class CDATA #REQUIRED >
<!ATTLIST depends selection ( select | wait ) #IMPLIED >

<!ELEMENT disability EMPTY >
<!ATTLIST disability code CDATA #REQUIRED >

<!ELEMENT email EMPTY >
<!ATTLIST email value CDATA #REQUIRED >

<!ELEMENT pin EMPTY >
<!ATTLIST pin value CDATA #IMPLIED >
<!ATTLIST pin required ( true | false ) #IMPLIED >

<!ELEMENT freeTime EMPTY >
<!ATTLIST freeTime days CDATA #REQUIRED >
<!ATTLIST freeTime endTime CDATA #REQUIRED >
<!ATTLIST freeTime length CDATA #IMPLIED >
<!ATTLIST freeTime startTime CDATA #REQUIRED >
<!ATTLIST freeTime time CDATA #IMPLIED >

<!ELEMENT groupAffiliation EMPTY >
<!ATTLIST groupAffiliation code CDATA #REQUIRED >

<!ELEMENT major EMPTY >
<!ATTLIST major code CDATA #REQUIRED >
<!ATTLIST major concentration CDATA #IMPLIED >
<!ATTLIST major degree CDATA #IMPLIED >
<!ATTLIST major weight CDATA #IMPLIED >

<!ELEMENT message ( #PCDATA ) >
<!ATTLIST message type CDATA #REQUIRED >

<!ELEMENT minor EMPTY >
<!ATTLIST minor code CDATA #REQUIRED >

<!ELEMENT name EMPTY >
<!ATTLIST name first CDATA #REQUIRED >
<!ATTLIST name last CDATA #REQUIRED >
<!ATTLIST name middle CDATA #IMPLIED >

<!ELEMENT notification ( student ) >
<!ATTLIST notification campus CDATA #REQUIRED >
<!ATTLIST notification year CDATA #REQUIRED >
<!ATTLIST notification term CDATA #REQUIRED >

<!ELEMENT request ( student+ ) >
<!ATTLIST request campus CDATA #REQUIRED >
<!ATTLIST request year CDATA #REQUIRED >
<!ATTLIST request term CDATA #REQUIRED >
<!ATTLIST request enrollments ( update | nochange | delete | import ) #IMPLIED >

<!ELEMENT requestSchedule ( courseOffering )* >
<!ATTLIST requestSchedule type ( commit | query ) #REQUIRED >

<!ELEMENT response ( student ) >
<!ATTLIST response campus CDATA #REQUIRED >
<!ATTLIST response year CDATA #REQUIRED >
<!ATTLIST response term CDATA #REQUIRED >

<!ELEMENT retrieveCourseRequests EMPTY >

<!ELEMENT schedule ( courseOffering | freeTime )* >
<!ATTLIST schedule type ( actual | proposed ) #REQUIRED >

<!ELEMENT student ( updateDemographics?, updateCourseRequests?, addCourseRequests?, dropCourseRequests?, requestSchedule?, retrieveCourseRequests?, cancelStudent?, acknowledgement?, courseRequests?, schedule?, message* ) >
<!ATTLIST student key CDATA #REQUIRED >

<!ELEMENT updateCourseRequests ( courseOffering | freeTime )* >
<!ATTLIST updateCourseRequests commit ( false | true ) #REQUIRED >
<!ATTLIST updateCourseRequests distribution ( dense | spread ) #IMPLIED >

<!ELEMENT addCourseRequests ( courseOffering | freeTime )* >
<!ATTLIST addCourseRequests commit ( false | true ) #REQUIRED >
<!ATTLIST addCourseRequests distribution ( dense | spread ) #IMPLIED >

<!ELEMENT dropCourseRequests ( courseOffering | freeTime )* >

<!ELEMENT updateDemographics ( name, email?, pin?, acadArea+, major*, minor*, disability*, groupAffiliation*) >
<!ATTLIST updateDemographics minCredit NMTOKEN #IMPLIED >
<!ATTLIST updateDemographics maxCredit NMTOKEN #IMPLIED >

<!ELEMENT preferences ( class | instructional-method )*>

<!ELEMENT instructional-method EMPTY>
<!ATTLIST instructional-method externalId CDATA #IMPLIED >
<!ATTLIST instructional-method name CDATA #IMPLIED >
<!ATTLIST instructional-method required ( false | true ) #IMPLIED >

=== UniTime/unitime/Documentation/Interfaces/Examples/studentSectioningResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE response PUBLIC "-//UniTime//DTD University Course Timetabling/EN" "http://www.unitime.org/interface/StudentSectioning.dtd">

<!-- 
 * UniTime 3.2 (University Timetabling Application)
 * Copyright (C) 2008 - 2010, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->

<response campus='puWestLafayetteTrdtn' year='2007' term='Fal'>
	<student key='123456'>
		<acknowledgement result='ok'> <!-- result is either ok or fail -->
			<message type='INFO'>Some message.</message>
			<message type='WARN'>Another message.</message>
		</acknowledgement>
		<courseRequests distribution='dense'> <!--  distribution is either dense or spread -->
			<courseOffering subjectArea='MA' courseNumber='101' waitlist='false' credit='4'>
				<alternative subjectArea='MA' courseNumber='102'/>
				<alternative subjectArea='MA' courseNumber='103'/>
			</courseOffering>
			<freeTime days='MWF' startTime='0730' endTime='0820' length='60'/>
			<!-- ... -->
			<courseOffering alternative='true' subjectArea='STAT' courseNumber='101' waitlist='false'>
				<alternative subjectArea='STAT' courseNumber='102'/>
				<!-- ... -->
			</courseOffering>
			<!-- ... -->
		</courseRequests>
		<schedule type='actual'> <!--  schedule is either actual or proposed -->
			<courseOffering subjectArea='MA' courseNumber='101'>
				<class id='1' assignmentId='1' name='Lecture' time='MWF 7:30a - 8:20a' date='Odd Wks' location='WTHR 200' instructor='Doe, Joe'
					days='MWF' startTime='0730' endTime='0820' note='Schedule note.'>
					<choice id='1:1' available='true' time='MWF 7:30a - 8:20a' date='Odd Wks' instructor='Doe, Joe' selection='select'/>
					<choice id='1:2' available='true' time='MWF 8:30a - 9:20a' date='Odd Wks' instructor='Doe, Joe'/>
					<choice id='1:3' available='false' time='MWF 8:30a - 9:20a' date='Odd Wks' instructor='Simpson, Bart' selection='wait'/>
				</class>
				<class id='2' assignmentId='2' name='Recitation' time='TTh 7:30a - 8:20a' location='WTHR 202, WTHR 203' days='TTh' startTime='0730' endTime='0820' parent='1'>
					<!-- parent: id of the parent class (to be able to indent classes) -->
					<choice id='2:1' available='true' time='TTh 7:30a - 8:20a' selection='select'>
						<depends class='1' choice='1:1' selection='select'/> <!--  this choice can only be selected when choice 1:1 of class 1 is selected -->
					</choice>
					<choice id='2:2' available='true' time='TTh 8:30a - 9:20a' selection='wait'>
						<!--  this choice can only be selected when either choice 1:2 or 1:3 of class 1 is selected -->
						<depends class='1' choice='1:2'/>
						<depends class='1' choice='1:3'/> 
					</choice>
				</class>
				<class id='3' assignmentId='3' name='Laboratory' time='F 10:30a - 12:20p' location='ENAD 402' days='F' startTime='1030' endTime='1220' parent='2'>
					<choice id='3:1' available='true' time='F 10:30a - 12:20p' selection='select'>
						<depends class='2' choice='2:1'/>
						<depends class='2' choice='2:2'>
							<depends class='1' choice='1:2'/>
						</depends>
					</choice>
					<choice id='3:2' available='false' time='F 12:30p - 2:20p' selection='wait'>
						<depends class='2' choice='2:2'>
							<depends class='1' choice='1:3'/>
						</depends>
					</choice>
					<choice id='3:3' available='true' time='F 2:30p - 4:20p' selection='wait'>
						<depends class='2' choice='2:1'/>
						<depends class='2' choice='2:2'>
							<depends class='1' choice='1:3'/>
						</depends>
					</choice>
				</class>
				<!-- possible choices for MA 101:
					Lecture MWF 7:30a - 8:20a WTHR 200 Doe, Joe
						Sel Que Time              Instructor
						(.)     MWF 7:30a - 8:20a Doe, Joe
						( )     MWF 8:30a - 9:20a Doe, Joe
						    [x] MWF 8:30a - 9:20a Simpson, Bart
					Recitation TTh 7:30a - 8:20a WTHR 202, WTHR 203
						Sel Que Time
						(.)     TTh 7:30a - 8:20a  (available when Lecture MWF 7:30 Doe, Joe is selected)
						( ) [x] TTh 8:30a - 9:20a  (available when Lecture MWF 8:30 Doe, Joe is selected, 
						                            wait-list when Lecture MWF 8:30 Simpson, Bart is wait-listed)
					Laboratory F 10:30a - 12:20p ENAD 402
						Sel Que Time
						(.)     F 10:30a - 12:20p  (available when Recitation TTh 7:30 is selected
						                            or available when Recitation TTh 8:30 is selected together with Lecture MWF 8:30a - 9:20a Doe, Joe is selected)
						    [x] F 12:30p -  2:20p  (wait-list when Recitation TTh 8:30 is selected together with Lecture MWF 8:30a - 9:20a Simpson, Bart is wait-listed)
						( ) [x] F  2:30p -  4:20p  (available when Recitation TTh 7:30 is selected,
						                            wait-list when Recitation TTh 8:30 is selected together with Lecture MWF 8:30a - 9:20a Simpson, Bart is wait-listed)
				 -->
			</courseOffering>
			<freeTime time='MWF 8:30a - 9:20a' days='MWF' startTime='0830' endTime='0920'/>
			<courseOffering subjectArea='MA' courseNumber='105' waitlist='true'/>
			<!-- ... -->
		</schedule>
	</student>
</response>

=== UniTime/unitime/Documentation/Interfaces/Examples/studentSectioningRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE request PUBLIC "-//UniTime//DTD University Course Timetabling/EN" "http://www.unitime.org/interface/StudentSectioning.dtd">

<!-- 
 * UniTime 3.2 (University Timetabling Application)
 * Copyright (C) 2008 - 2010, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->

<request campus='puWestLafayetteTrdtn' year='2007' term='Fal'>
	<student key='123456'>
		<updateDemographics> <!-- 0..1 -->
			<name first='Joe' middle='B' last='Doe'/>
			<email value='joe.doe@purdue.edu'/>
			<acadArea abbv='CFS' classification='X'> <!-- 1..* -->
				<major code='ABC'/> <!-- 0..* -->
				<minor code='DDD'/> <!-- 0..* -->
			</acadArea>
			<major code='ABC'/>  <!--  0..*, when there is no relation between academic areas and majors  -->
			<minor code='DDD'/> <!--  0..*, when there is no relation between academic areas and minors -->
			<disability code=''/> <!-- 0..* -->
			<groupAffiliation code='YngExp'/> <!-- 0..* -->
		</updateDemographics>
		<updateCourseRequests commit='true' distribution='dense'> <!-- 0..1 -->
			<!-- distribution is either dense or spread -->
			<!-- (course offering, free time) requests in the order of priorities -->
			<courseOffering subjectArea='MA' courseNumber='101' waitlist='false' credit='4'>
				<alternative subjectArea='MA' courseNumber='102'/>
				<alternative subjectArea='MA' courseNumber='103'/>
			</courseOffering>
			<!-- FREE TIME REQUESTS -->
			<freeTime days='MWF' startTime='0730' endTime='0820' length='60'/>
			<!-- alternative course requests -->
			<courseOffering subjectArea='STAT' courseNumber='101' waitlist='false' alternative='true'>
				<alternative subjectArea='STAT' courseNumber='102'/>
				<!-- ... -->
			</courseOffering>
			<!-- ... -->
		</updateCourseRequests>
		<requestSchedule type='query'>
			<!--  type is either query or commit -->
			<courseOffering subjectArea='MA' courseNumber='101'>
				<class id='1' assignmentId='1'>
					<choice id='1:2' selection='select'/>
					<choice id='1:3' selection='wait'/>
				</class>
				<class id='2' assignmentId='2'>
					<choice id='2:2' selection='select'/>
					<choice id='2:2' selection='wait'/>
				</class>
				<class id='3' assignmentId='3'>
					<choice id='3:1' selection='select'/> <!--  0..1 choice selected, 0..* choice wait-listed -->
					<choice id='3:2' selection='wait'/>
					<choice id='3:3' selection='wait'/>
				</class>
				<!-- selection for MA 101 (see the example below):
					Lecture MWF 7:30a - 8:20a WTHR 200 Doe, Joe
						Sel Que Time              Instructor
						( )     MWF 7:30a - 8:20a Doe, Joe
						(.)     MWF 8:30a - 9:20a Doe, Joe
						    [x] MWF 8:30a - 9:20a Simpson, Bart
					Recitation TTh 7:30a - 8:20a WTHR 202, WTHR 203
						Sel Que Time
						( )     TTh 7:30a - 8:20a
						(.) [x] TTh 8:30a - 9:20a
					Laboratory F 10:30a - 12:20p ENAD 402
						Sel Que Time
						(.) [ ] F 10:30a - 12:20p
						    [x] F 12:30p -  2:20p
						    [x] F  2:30p -  4:20p
				 -->
			</courseOffering>
			<courseOffering subjectArea='MA' courseNumber='105' waitlist='true'/>
			<!-- ... -->
		</requestSchedule>
		<retrieveCourseRequests/>
		<cancelStudent/>
	</student>
</request>
