=== UniTime/unitime/Documentation/Interfaces/Student.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->

<!-- Element acadAreaClass is deprecated in UniTime 4.2, use major.academicClass and minor.academicClass instead. -->
<!ELEMENT acadAreaClass EMPTY >
<!ATTLIST acadAreaClass academicArea CDATA #REQUIRED >
<!ATTLIST acadAreaClass academicClass CDATA #REQUIRED >

<!ELEMENT major EMPTY >
<!ATTLIST major academicArea CDATA #REQUIRED >
<!-- Attribute major.academicClass since UniTime 4.2 -->
<!ATTLIST major academicClass CDATA #IMPLIED >
<!ATTLIST major code CDATA #REQUIRED >
<!ATTLIST major concentration CDATA #IMPLIED >
<!ATTLIST major degree CDATA #IMPLIED >
<!ATTLIST major weight CDATA #IMPLIED >

<!ELEMENT minor EMPTY >
<!ATTLIST minor academicArea CDATA #REQUIRED >
<!-- Attribute minor.academicClass since UniTime 4.2 -->
<!ATTLIST minor academicClass CDATA #IMPLIED >
<!ATTLIST minor code CDATA #REQUIRED >

<!ELEMENT studentGroup EMPTY >
<!ATTLIST studentGroup group CDATA #REQUIRED >

<!ELEMENT studentAccomodation EMPTY >
<!ATTLIST studentAccomodation accomodation CDATA #REQUIRED >

<!ELEMENT student ( studentAcadAreaClass?, studentMajors, studentMinors?, studentGroups?, studentAccomodations? ) >
<!ATTLIST student externalId CDATA #REQUIRED >
<!ATTLIST student firstName CDATA #REQUIRED >
<!ATTLIST student lastName CDATA #REQUIRED >
<!ATTLIST student middleName CDATA #IMPLIED >
<!ATTLIST student email CDATA #IMPLIED >
<!ATTLIST student minCredit NMTOKEN #IMPLIED >
<!ATTLIST student maxCredit NMTOKEN #IMPLIED >
<!ATTLIST student pin CDATA #IMPLIED >
<!ATTLIST student pinReleased ( false | true ) #IMPLIED >

<!ELEMENT studentAcadAreaClass ( acadAreaClass+ ) >

<!ELEMENT studentMajors ( major+ ) >

<!ELEMENT studentMinors ( minor* ) >

<!ELEMENT studentGroups ( studentGroup* ) >

<!ELEMENT studentAccomodations ( studentAccomodation* ) >

<!ELEMENT students ( student+ ) >
<!ATTLIST students campus CDATA #REQUIRED >
<!ATTLIST students term CDATA #REQUIRED >
<!ATTLIST students year CDATA #REQUIRED >
<!ATTLIST students incremental ( false | true ) "false" >

=== UniTime/unitime/branches/dev_exam/Documentation/Interfaces/Examples/studentInfoImport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students PUBLIC "-//UniTime//DTD University Course Timetabling/EN" "http://www.unitime.org/interface/Student.dtd">

<!-- 
 * UniTime 3.0 (University Timetabling Application)
 * Copyright (C) 2007, UniTime.org
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 -->
	<!-- student                 ==> Required:  externalId, firstName, lastName
	                                 Optional:  middleName, email
	       studentAcadAreaClass  ==> [1 ==> N entries]
	         acadAreaClass       ==> Required:  academicArea, academicClass
	       studentMajors         ==> [1 ==> N entries]  
	         major               ==> Required:  academicArea, code
	       studentMinors         ==> [0 ==> N entries]  
	         minor               ==> Required:  academicArea, code
	       studentGroups         ==> [0 ==> N entries]  
	         studentGroup        ==> Required:  group
	       studentAccomodations  ==> [0 ==> N entries]  
	         studentAccomodation ==> Required:  accomodation
	-->
<students campus="puWestLafayetteTrdtn" term="Fal" year="2007">
	<student externalId="99999111110" firstName="JO DEAN" middleName="KAY" lastName="TIPTON">
   		<studentAcadAreaClass>
   			<acadAreaClass academicArea="CFS" academicClass="08"/>
  		</studentAcadAreaClass>
  		<studentMajors>
   			<major academicArea="CFS" code="314"/>
  		</studentMajors>
  		<studentMinors>
   			<minor academicArea="CFS" code="349"/>
  		</studentMinors>
	</student>
	<student externalId="99999111111" firstName="KRISTY" middleName="N" lastName="DERUITER">
 		<studentAcadAreaClass>
   			<acadAreaClass academicArea="GR" academicClass="M"/>
  		</studentAcadAreaClass>
  		<studentMajors>
   			<major academicArea="GR" code="D30"/>
  		</studentMajors>
	</student>
	<student externalId="99999111112" firstName="TAUNA" middleName="STARBUCK" lastName="SISCO" email="tssisco@msn.com">
  		<studentAcadAreaClass>
   			<acadAreaClass academicArea="GR" academicClass="A"/>
  		</studentAcadAreaClass>
  		<studentMajors>
   			<major academicArea="GR" code="J77"/>
  		</studentMajors>
		<studentGroups>
		    <studentGroup group="AgEd"/>
		</studentGroups>
		<studentAccomodations>
		    <studentAccomodation accomodation="Visual"/>
		    <studentAccomodation accomodation="WChair"/>
		</studentAccomodations>
	</student>
	<student externalId="99999111113" firstName="LAUREN" middleName="DAKE" lastName="O NEIL">
   		<studentAcadAreaClass>
   			<acadAreaClass academicArea="LA" academicClass="07"/>
			<acadAreaClass academicArea="ME" academicClass="9"/>
   		</studentAcadAreaClass>
   		<studentMajors>
  			<major academicArea="LA" code="466"/>
			<major academicArea="ME" code="331"/>
   		</studentMajors>
   	</student>
</students>
